name: ems
description: "Employee Management System"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: any
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.0.11
#  shared_preferences: ^2.0.15
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:
  freezed: ^2.5.0
  json_serializable:
  retrofit_generator:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/
